
import React from 'react';
import { Player, PlayerStats } from '../types';

interface SocialShareCardProps {
  teamName: string;
  opponentName: string;
  leftScore: number;
  rightScore: number;
  date: string;
  possession: number;
  scorers: { name: string; tries: number }[];
}

export const SocialShareCard: React.FC<SocialShareCardProps> = ({
  teamName,
  opponentName,
  leftScore,
  rightScore,
  date,
  possession,
  scorers
}) => {
  const isWin = leftScore > rightScore;
  const resultText = isWin ? 'VICTORY' : leftScore === rightScore ? 'DRAW' : 'FULL TIME';
  const resultColor = isWin ? 'bg-green-500' : 'bg-slate-900';

  return (
    <div className="flex flex-col items-center">
      <div id="social-card" className="w-[400px] h-[500px] bg-slate-900 relative overflow-hidden flex flex-col text-white font-sans shrink-0 shadow-2xl rounded-none">
        {/* Background Accents */}
        <div className="absolute top-0 right-0 w-64 h-64 bg-red-600/20 rounded-full blur-3xl -mr-16 -mt-16"></div>
        <div className="absolute bottom-0 left-0 w-64 h-64 bg-blue-600/10 rounded-full blur-3xl -ml-16 -mb-16"></div>
        
        {/* Header */}
        <div className="relative z-10 p-8 text-center border-b border-white/10">
          <div className="inline-block px-3 py-1 rounded-full border border-white/20 text-[10px] font-bold tracking-[0.2em] uppercase mb-4">
            {date}
          </div>
          <h2 className={`text-4xl font-heading font-black tracking-tighter mb-1 ${isWin ? 'text-green-400' : 'text-white'}`}>
            {resultText}
          </h2>
          <div className="w-12 h-1 bg-red-600 mx-auto rounded-full mt-4"></div>
        </div>

        {/* Score Board */}
        <div className="relative z-10 flex-1 flex flex-col justify-center px-8">
           <div className="flex justify-between items-center mb-2">
              <span className="text-xl font-heading font-bold uppercase tracking-wider text-gray-300">{teamName}</span>
              <span className="text-5xl font-heading font-black">{leftScore}</span>
           </div>
           <div className="flex justify-between items-center mb-8">
              <span className="text-xl font-heading font-bold uppercase tracking-wider text-gray-500">{opponentName}</span>
              <span className="text-5xl font-heading font-black text-gray-500">{rightScore}</span>
           </div>

           {/* Stats */}
           <div className="grid grid-cols-2 gap-4 border-t border-white/10 pt-6">
              <div>
                 <span className="block text-[10px] font-bold text-gray-500 uppercase tracking-widest mb-1">Possession</span>
                 <span className="text-2xl font-bold">{possession}%</span>
              </div>
              <div className="text-right">
                 <span className="block text-[10px] font-bold text-gray-500 uppercase tracking-widest mb-1">Top Scorers</span>
                 <div className="text-sm font-medium">
                   {scorers.length > 0 ? (
                     scorers.slice(0, 2).map((s, i) => (
                       <div key={i}>{s.name} <span className="text-red-500">({s.tries})</span></div>
                     ))
                   ) : (
                     <span className="text-gray-600">-</span>
                   )}
                 </div>
              </div>
           </div>
        </div>

        {/* Footer */}
        <div className="relative z-10 p-4 bg-black/20 text-center">
           <p className="text-[10px] font-bold text-gray-500 uppercase tracking-[0.2em]">Generated by LeagueLens</p>
        </div>
      </div>
      
      <p className="mt-4 text-sm text-gray-500">Take a screenshot of this card to share on social media.</p>
    </div>
  );
};
